# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3ef6b80e7756f70eef32530387226443cd474bdc227eb6703a6db73e39152c26921f4346e435cbbda6a96ff53cca3f4cdd1062cace4ac0fa68df9cd64f9600

test:
  secret_key_base: 32ce4e7456fdbd687cde3db7f07c6ffde1006c44d50d313338abb30ab6d9dcec359311340ae403d524114bcff7746beeb0d6747b3c412a33429f84d19c7df978

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
